### PR TITLE
Use Emitter class

### LINKED ISSUE #57: Uncaught TypeError: undefined is not a function, When run test-status:run-tests
Now git head Atom fail `test-status:run-tests`.

I guess, atom.emit function is removed. And use [Emitter class](https://atom.io/docs/api/latest/Emitter).

**Atom Version**: 0.206.0-4941229
**System**: Mac OS X 10.10.3
**Thrown From**: [test-status](https://github.com/tombell/test-status) package, v0.33.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/tomoya/src/github.com/tomoya/dotfiles/.atom/packages/test-status/lib/command-runner.coffee:71

TypeError: undefined is not a function
  at ChildProcess.<anonymous> (/Users/tomoya/src/github.com/tomoya/dotfiles/.atom/packages/test-status/lib/command-runner.coffee:71:16)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Socket.<anonymous> (child_process.js:1166:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### PR DESCRIPTION
**Pull request by tomoya**
An instant fix #57

### CODE REVIEW

**Comment by tombell** [comment]
They're used for keymaps (https://github.com/tombell/test-status/blob/master/keymaps/test-status.cson).

**Comment by tombell** [comment]
I believe I added the events so that other packages could listen to them and hook into test success/failure.

**Comment by tomoya** [comment]
@tombell 
Thank you for merge it.
test-status works on atom@0.206.0-d44aeb2

This package is my best. Thank you very much.

@walles 
Your suggest is correct. I think there is a better way.
However, I have priority to turn off the Uncaught TypeError. I'd like to someday investigate.
